In [3]:
import numpy as np

a = np.linspace(0,1,5)

In [5]:
x,y=np.meshgrid(a,a)

In [6]:
x

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [7]:
y

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  , 1.  , 1.  ]])

In [12]:
pt = list(zip(x.flat,y.flat))

In [13]:
pt

[(0.0, 0.0),
 (0.25, 0.0),
 (0.5, 0.0),
 (0.75, 0.0),
 (1.0, 0.0),
 (0.0, 0.25),
 (0.25, 0.25),
 (0.5, 0.25),
 (0.75, 0.25),
 (1.0, 0.25),
 (0.0, 0.5),
 (0.25, 0.5),
 (0.5, 0.5),
 (0.75, 0.5),
 (1.0, 0.5),
 (0.0, 0.75),
 (0.25, 0.75),
 (0.5, 0.75),
 (0.75, 0.75),
 (1.0, 0.75),
 (0.0, 1.0),
 (0.25, 1.0),
 (0.5, 1.0),
 (0.75, 1.0),
 (1.0, 1.0)]

In [17]:
y=np.array(pt)

In [18]:
y.shape

(25, 2)

In [19]:
y

array([[0.  , 0.  ],
       [0.25, 0.  ],
       [0.5 , 0.  ],
       [0.75, 0.  ],
       [1.  , 0.  ],
       [0.  , 0.25],
       [0.25, 0.25],
       [0.5 , 0.25],
       [0.75, 0.25],
       [1.  , 0.25],
       [0.  , 0.5 ],
       [0.25, 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.5 ],
       [1.  , 0.5 ],
       [0.  , 0.75],
       [0.25, 0.75],
       [0.5 , 0.75],
       [0.75, 0.75],
       [1.  , 0.75],
       [0.  , 1.  ],
       [0.25, 1.  ],
       [0.5 , 1.  ],
       [0.75, 1.  ],
       [1.  , 1.  ]])

In [25]:
z=np.expand_dims(y,axis=1)


In [26]:
z

array([[[0.  , 0.  ]],

       [[0.25, 0.  ]],

       [[0.5 , 0.  ]],

       [[0.75, 0.  ]],

       [[1.  , 0.  ]],

       [[0.  , 0.25]],

       [[0.25, 0.25]],

       [[0.5 , 0.25]],

       [[0.75, 0.25]],

       [[1.  , 0.25]],

       [[0.  , 0.5 ]],

       [[0.25, 0.5 ]],

       [[0.5 , 0.5 ]],

       [[0.75, 0.5 ]],

       [[1.  , 0.5 ]],

       [[0.  , 0.75]],

       [[0.25, 0.75]],

       [[0.5 , 0.75]],

       [[0.75, 0.75]],

       [[1.  , 0.75]],

       [[0.  , 1.  ]],

       [[0.25, 1.  ]],

       [[0.5 , 1.  ]],

       [[0.75, 1.  ]],

       [[1.  , 1.  ]]])